name: Minute Workflow

on:
  schedule:
    - cron: '* * * * *'  # Runs every minute

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add your desired workflow steps here

      - name: Save file to main branch
        run: |
          echo "Current time: $(date)" > file.txt
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git checkout main
          git add file.txt
          git commit -m "Save file with current time to main branch"
          git push origin main

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: saved-file
          path: file.txt

