name: Minute Workflow

on:
  schedule:
    - cron: '* * * * *'  # Runs every minute

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: create file
        run: 'echo "Current time: $(date)" > file.txt'
        
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4        

