name: Write to File

on:
  push:
    branches:
      - main

jobs:
  write:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Write to file
        run: echo 'Hello, World!' > output.txt

      - name: Commit changes
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add output.txt
          git commit -m "Update output.txt" --author="${GITHUB_ACTOR}"
          git push
